#!/bin/bash

DC='dc='$(echo ${LDAP_DOMAIN_BASE} | cut -d "." -f 1)',dc='$(echo ${LDAP_DOMAIN_BASE} | cut -d "." -f 2)

if [ "$(basename $0)" == "add_domain" ] ; then
	echo -n "Domain? "
	read DOMAIN

	cat > /tmp/domain.ldif <<EOF
dn:dc=$DOMAIN,dc=mail,$DC
o: $(echo $DOMAIN | sed -r 's/(.*)\.(.*)/\1\2/')
dc: $DOMAIN
description: virtualDomain
objectClass: top
objectClass: dcObject
objectClass: organization

dn:dc=mailAccount,dc=$DOMAIN,dc=mail,$DC
dc: mailAccount
o: mailAccount
objectClass: top
objectClass: dcObject
objectClass: organization

dn:dc=mailAlias,dc=$DOMAIN,dc=mail,$DC
dc: mailAlias
o: mailAlias
objectClass: top
objectClass: dcObject
objectClass: organization
EOF

	ldapadd -x -h ldap -D cn=admin,$DC -w ${LDAP_PASSWORD} -f /tmp/domain.ldif
fi

if [ "$(basename $0)" == "add_alias" ]; then
	echo -n 'Domain? '
	read DOMAIN
	echo -n 'User? '
	read USER
	echo -n 'Name? '
	read NAME
	echo 'Recipient list? CTRL+D to finish'
	while read DEST; do
	 USERS="$USERS\nmaildrop:$DEST"
	done

	USER=$(echo $USER | tr 'A-Z' 'a-z')
	cat > '/tmp/alias.ldif' <<EOF
dn:mail=$USER@$DOMAIN,dc=mailAlias,dc=$DOMAIN,dc=mail,$DC
cn:$USER@$DOMAIN
mail:$USER@$DOMAIN
EOF
	echo -e $USERS | grep maildrop >> /tmp/alias.ldif
	cat >> '/tmp/alias.ldif' <<EOF
sn: $NAME
displayName: $NAME
objectClass: top
objectClass: inetOrgPerson
objectClass: CourierMailAlias
EOF

	ldapadd -x -h ldap -D cn=admin,$DC -w ${LDAP_PASSWORD} -f '/tmp/alias.ldif'
fi

if [ "$(basename $0)" == "add_email" ]; then
	echo -n "Domain? "
	read DOMAIN
	echo -n "User? "
	read USER
	OLDMODES=$(stty -g)
	stty -echo
	echo 'Password? '
	read PASSWORD
	stty $OLDMODES

	USER=$(echo $USER | tr 'A-Z' 'a-z')
	if [ $(ldapsearch -h ldap -b "ou=people,$DC" -D "cn=admin,$DC" -w "$LDAP_PASSWORD" -P 3 -LLL "(mail=$USER)" uid | wc -l ) -eq 0 ]; then
		cat > '/tmp/account.ldif' <<EOF
dn:mail=$USER@$DOMAIN,dc=mailaccount,dc=$DOMAIN,dc=mail,$DC
cn:$USER@$DOMAIN
sn:$USER
mail:$USER@$DOMAIN
mailbox: $DOMAIN/$USER/
homeDirectory: /vmail/
objectClass: top
objectClass: inetOrgPerson
objectClass: CourierMailAccount
userPassword: $(slappasswd -s $PASSWORD -h {SSHA})
EOF
		ldapadd -x -h ldap -D cn=admin,$DC -w ${LDAP_PASSWORD} -f /tmp/account.ldif
	fi
fi
