#!/bin/bash

if [ -f "/var/run/mail-openldap.starting" ]; then
	exit 0
fi

procs=$(ps ax)

echo "${procs}"|grep -q dovecot || exit 1
echo "${procs}"|grep -q postfix || exit 1
echo "${procs}"|grep -q opendkim || exit 1
echo "${procs}"|grep -q saslauthd || exit 1

exit 0
