#!/bin/bash

source /usr/share/mail-openldap/common

exitvalue=0

unhealthy() {
	echo "$*"
	exitvalue=1
}

if [ -f "/var/run/mail-openldap.starting" ]; then
	exit "${exitvalue}"
fi

procs=$(ps ax)

echo "${procs}"|grep -q dovecot || unhealthy 'dovecot is not running'
echo "${procs}"|grep -q postfix || unhealthy 'postfix is not running'
echo "${procs}"|grep -q opendkim || unhealthy 'opendkim is not running'
echo "${procs}"|grep -q saslauthd || unhealthy 'saslauthd is not running'

me=$(ldapwhoami ${LDAP_OPTS})
[ "${me}" != "dn:${CN_ADMIN}" ] && unhealthy "LDAP issue: ${me}"

exit "${exitvalue}"
