#!/bin/bash

status() {
	echo>&2 "---> ${@}"
}

DC="dc=$(echo $LDAP_DOMAIN_BASE|cut -d'.' -f1),dc=$(echo $LDAP_DOMAIN_BASE|cut -d'.' -f2)"
CN_ADMIN="cn=admin,$DC"
LDAP_OPTS="-x -h ldap -D $CN_ADMIN -w $LDAP_PASSWORD"

setValue() {
  VAR=$(echo $2 | sed 's#\([]\#\%\@\*\$\/&[]\)#\\\1#g')
  sed -i "s/^#\?\($1[[:space:]]*=\).*$/\1$VAR/" $3
}

uncomment() { sed -i "$1"' s/^ *#//' "$2"; }
comment()   { sed -i "$1"' s/^/#/' "$2"; }

genPwd() {
  date +%s | sha256sum | base64 | head -c 32 ; echo 
}

replaceValues() { 
  filename=$1
  shift
  ans=$(cat $filename) 
 
  while [ $# -gt 1 ]; do
		from=%"$1"
		to="$2"
    shift 2
    ans=$(echo "$ans"|sed "s$'\001'$from$'\001'$to$'\001'g")
  done                                                                                                    
  echo "$ans"
} 
